name: apple_shop
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6 
  smooth_page_indicator: ^1.1.0 
  dotted_line: ^3.2.2
  hexcolor: ^3.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  
  assets: 
    - images/

  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800

    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900

    - family: Sh
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500      
